POST http://localhost:8080/api/comment HTTP/1.1
Content-Type: application/json

{
  "text": "Good Trip",
  "userId": "3",
  "vacationId": "2"
}

###
GET http://localhost:8080/api/username/admin HTTP/1.1


###

GET http://localhost:8080/api/location HTTP/1.1

###
GET http://localhost:8080/api/vacation/ HTTP/1.1

###
GET http://localhost:8080/api/vacation/vid/1 HTTP/1.1

###
POST  http://localhost:8080/api/vacation/ HTTP/1.1
Content-Type: application/json
Accept: application/json
{ "vacationId": 0, 
  "description": "Nice trip to the beach", 
  "leasureLevel": "3"}

###
GET  http://localhost:8080/api/comment/vid/1 HTTP/1.1

###
POST http://localhost:8080/api/comment/vid/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
{ "commentId": 0,
  "text": "test comment",
  "userId": 1,
  "vacationId": 1}